### PR TITLE
Added Parallax Scrolling

### LINKED ISSUE #29: Implement parallax scrolling to create depth

### LINKED ISSUE #30: Ensure Background image scrolls smoothly with the player movement

### LINKED ISSUE #31: Implement Background

### PR DESCRIPTION
**Pull request by GoatEXE**
Targeting Issues #30, #29

## Changes
Given a (rather unappealing) placeholder image (dimensions are 2500x987), 2 nodes were added to the main scene:

- CanvasLayer("ParallaxLayer")
  - Layer: -1
  - Follow Viewport: Enabled
  - Scale: 0.25
- TextureRect("Background")
  - Layout > Transform
    - Size (x: 5000, y: 1200)
    - Position (x: -2050, y: -10)

## Description

- Verified movement is smooth according to the scaling of the ParallaxLayer.
- A negative layer puts the image behind other nodes with a higher layer.
- The smaller the scale, the farther away the background appears. In other words, the background moves much slower with a smaller scaling. 
- The sizing and positioning is approximate to consider the left, right, and bottom boundaries for the test environment (I did not fly to upper boundary).  

## Moving Forward
Will need a replacement background that doesn't burn my retinas. Referencing #28

### CODE REVIEW

**Comment by LarsenEndeavors** [comment]
Not much to comment on here, though I did look at some ways we can manually set up that offset for the Viewport, that way we can have sliders, idk if we'll need it but it's good to know it's a thing.

**Review by LarsenEndeavors — COMMENTED** [review]
Looks good man

**Comment by LarsenEndeavors** [comment]
There is one thing

> Size (x: 5000, y: 1200)
> 
> Position (x: -2050, y: -10)

This seems arbitrary, why did you pick these numbers?

**Comment by GoatEXE** [comment]
> This seems arbitrary, why did you pick these numbers?

There's still some grey space here for me. Mainly, I adjusted these numbers until I found a fluid background for the given playable area. Since the background image is 2500x987, I reduced the scaling to 0.25 (for a more distant ambiance) and scaled the size up until I found no grey background on any playable background. When an image is scaled up, it only expands toward the bottom and right, so positioning must also be adjusted to center that image.

I'm sure there's a general guideline or science for sizing, positioning, and scaling, but I'm not sure what exactly that is yet. My biggest takeaway is the scaling. If you want the background to be right next to you, have a scaling close to 1.

**Pull request merged**
